// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm1Y-mKXyUFi6WZ4Tjj1lLymfQ308jsQU',
    appId: '1:995839914241:web:e849324372995a73f12b00',
    messagingSenderId: '995839914241',
    projectId: 'zenda-app',
    authDomain: 'zenda-app.firebaseapp.com',
    storageBucket: 'zenda-app.firebasestorage.app',
    measurementId: 'G-D66QX7FSML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcaR0gOFPJbNVYslEzLOq2TrH8gEq1clE',
    appId: '1:995839914241:android:30f07d2da4852ed1f12b00',
    messagingSenderId: '995839914241',
    projectId: 'zenda-app',
    storageBucket: 'zenda-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj-aaWuujM1W9GG2ff0coZA_-TaASY3XU',
    appId: '1:995839914241:ios:c031308093a4cd94f12b00',
    messagingSenderId: '995839914241',
    projectId: 'zenda-app',
    storageBucket: 'zenda-app.firebasestorage.app',
    iosBundleId: 'com.example.instaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj-aaWuujM1W9GG2ff0coZA_-TaASY3XU',
    appId: '1:995839914241:ios:c031308093a4cd94f12b00',
    messagingSenderId: '995839914241',
    projectId: 'zenda-app',
    storageBucket: 'zenda-app.firebasestorage.app',
    iosBundleId: 'com.example.instaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm1Y-mKXyUFi6WZ4Tjj1lLymfQ308jsQU',
    appId: '1:995839914241:web:a12ea04b798313eaf12b00',
    messagingSenderId: '995839914241',
    projectId: 'zenda-app',
    authDomain: 'zenda-app.firebaseapp.com',
    storageBucket: 'zenda-app.firebasestorage.app',
    measurementId: 'G-FT8H6J6BL5',
  );
}
